"""Regression guards for the 2026-06 installer deploy-blocker sweep.

Each test pins a descriptor value that — if reverted — reproduces a crash-loop the
installer actually shipped to the live master (Правила Карпатого #7/#10/#12). All
are pure descriptor assertions: fast, no Docker, backend-agnostic.
"""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from agmind.schemas import ServiceDescriptor

pytestmark = pytest.mark.backend_any

SERVICES_DIR = Path(__file__).resolve().parent.parent.parent / "templates" / "services"


def _load(name: str) -> ServiceDescriptor:
    data = yaml.safe_load((SERVICES_DIR / f"{name}.yaml").read_text(encoding="utf-8"))
    return ServiceDescriptor.model_validate(data)


def test_llama_llm_flash_attn_carries_required_value() -> None:
    """The b9049 llama-server build made --flash-attn take a REQUIRED enum value
    (on|off|auto). A bare --flash-attn swallows the next flag (--cache-type-k) as
    its value and crash-loops the container (Правила #7)."""
    cmd = [str(c) for c in (_load("llama-llm").command or [])]
    valid = {"on", "off", "auto", "true", "false"}
    for i, tok in enumerate(cmd):
        if tok.startswith("--flash-attn="):
            assert tok.split("=", 1)[1].lower() in valid, f"bad --flash-attn value: {tok}"
            return
        if tok == "--flash-attn":
            nxt = cmd[i + 1] if i + 1 < len(cmd) else None
            assert nxt is not None and not nxt.startswith("-") and nxt.lower() in valid, (
                "bare --flash-attn swallows the next flag as its value; b9049 "
                f"requires on|off|auto, next token is {nxt!r}"
            )
            return


def test_llama_rerank_carries_parallel_slots() -> None:
    """Phase 14 (M9.C, D-01): rerank batches concurrent requests same as llama-embed
    already does. A hardcoded --parallel 2 token pair (no env var — rerank has zero
    existing tunability infra, per RESEARCH minimal-diff recommendation)."""
    cmd = [str(c) for c in (_load("llama-rerank").command or [])]
    assert "--parallel" in cmd, "llama-rerank command missing --parallel"
    idx = cmd.index("--parallel")
    nxt = cmd[idx + 1] if idx + 1 < len(cmd) else None
    assert nxt == "2", f"expected --parallel 2, got next token {nxt!r}"


def test_milvus_storage_type_not_deprecated_minio() -> None:
    """Milvus v2.6 storage-V2 arrow filesystem accepts only {local, remote,
    opendal}; the legacy 'minio' token panics at boot. MinIO stays the backend
    via MINIO_ADDRESS — the storage TYPE must be the scheme, not the backend."""
    env = _load("milvus").env or {}
    storage_type = env.get("COMMON_STORAGETYPE", "remote")
    assert storage_type in {"local", "remote", "opendal"}, (
        f"COMMON_STORAGETYPE={storage_type!r} is rejected by Milvus v2.6"
    )
    assert storage_type != "minio", "'minio' removed in v2.6 — use 'remote'"
    assert env.get("MINIO_ADDRESS") == "milvus-minio:9000"


def test_dify_plugin_daemon_has_required_env() -> None:
    """The dify-plugin-daemon image fails config validation one key at a time;
    the descriptor must ship the full required env set (Правила #10)."""
    env = _load("dify-plugin-daemon").env or {}
    required = {
        "DB_HOST",
        "DB_PORT",
        "DB_USERNAME",
        "DB_PASSWORD",
        "DB_DATABASE",
        "REDIS_HOST",
        "REDIS_PORT",
        "SERVER_KEY",
        "DIFY_INNER_API_URL",
        "DIFY_INNER_API_KEY",
    }
    assert required <= set(env), f"dify-plugin-daemon missing env: {sorted(required - set(env))}"
    assert "${POSTGRES_PASSWORD" in env["DB_PASSWORD"], (
        "must use our postgres password, not image default"
    )
    assert env["DIFY_INNER_API_URL"] == "http://dify-api:5001"


def test_dify_inner_api_key_parity_between_api_and_daemon() -> None:
    """The inner-API handshake only authenticates if api and daemon share the
    SAME secret refs (Правила #12)."""
    api = _load("dify-api").env or {}
    daemon = _load("dify-plugin-daemon").env or {}
    assert daemon["DIFY_INNER_API_KEY"] == api["INNER_API_KEY_FOR_PLUGIN"]
    assert daemon["SERVER_KEY"] == api["PLUGIN_DAEMON_KEY"]


def test_dify_plugin_secrets_are_generated_and_required() -> None:
    """The ${DIFY_PLUGIN_*} refs must be generated into .env, else compose runs on
    the changeme defaults and the handshake is insecure/inconsistent (Правила #10/#11)."""
    from agmind.install.steps import _RUNTIME_SECRET_KEYS
    from agmind.install.verify import REQUIRED_RUNTIME_ENV_KEYS

    for key in ("DIFY_PLUGIN_DAEMON_KEY", "DIFY_PLUGIN_INNER_API_KEY"):
        assert key in _RUNTIME_SECRET_KEYS, f"{key} must be generated by EnvWriteStep"
        assert key in REQUIRED_RUNTIME_ENV_KEYS, f"{key} must be asserted by install-verify"
