"""CI gate (Правила Карпатого #10/#11): every REQUIRED ${VAR} a descriptor
interpolates must be generated by EnvWriteStep (or carry a `:-default`).

This is the generic form of the dify-plugin-daemon deploy-blocker that slipped to
the live operator: a referenced-but-ungenerated secret renders to empty and
crash-loops only on `agmind install`. Fail CLOSED here so the whole class is
caught in CI, not on the operator's first install. The set-diff is clean today;
this guard keeps it clean for every future descriptor + generator change.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from agmind.install.steps import (
    _ALERTMANAGER_TELEGRAM_KEYS,
    _AUTHELIA_SECRET_KEYS,
    _RUNTIME_SECRET_KEYS,
)

pytestmark = pytest.mark.backend_any

SERVICES_DIR = Path(__file__).resolve().parent.parent.parent / "templates" / "services"

# Keys EnvWriteStep always writes via _runtime_env() that are not secret tuples.
_EXTRA_GENERATED = {"MINIO_ROOT_USER", "N8N_TIMEZONE"}

# A ${VAR} ref with NO `:-default`: either bare ${VAR} or required ${VAR:?msg}.
# (`${VAR:-default}` does not match — the renderer is fine with those.)
_REQUIRED_REF = re.compile(r"\$\{([A-Z][A-Z0-9_]*)(:\?[^}]*)?\}")


def _generated_keys() -> set[str]:
    return (
        set(_RUNTIME_SECRET_KEYS)
        | set(_AUTHELIA_SECRET_KEYS)
        | set(_ALERTMANAGER_TELEGRAM_KEYS)
        | _EXTRA_GENERATED
    )


def _required_refs() -> set[str]:
    refs: set[str] = set()
    for path in SERVICES_DIR.glob("*.yaml"):
        for match in _REQUIRED_REF.finditer(path.read_text(encoding="utf-8")):
            refs.add(match.group(1))
    return refs


def test_every_required_descriptor_var_is_generated() -> None:
    missing = sorted(_required_refs() - _generated_keys())
    assert not missing, (
        "these ${VAR} are referenced (no :-default) by a service descriptor but are "
        "NOT generated by EnvWriteStep -> they render to empty -> crash-loop on a "
        f"clean `agmind install`. Add them to agmind/install/steps.py generators or "
        f"give them a :-default: {missing}"
    )
