"""Crash-loop blocker fix: Authelia EROFS + missing config.

authelia.yaml mounted /config :ro, but Authelia (root) chowns /config AND
auto-generates configuration.yml there -> EROFS fatal crash loop, and no config was
ever shipped. Fix: writable /config, ship a minimal valid 4.39 config + users file
(domain-templated), secrets via the runtime .env (AUTHELIA_* env, read by Authelia).
"""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from agmind.services.renderer import load_descriptors

pytestmark = pytest.mark.backend_any

_REPO = Path(__file__).resolve().parents[2]
_AUTH_DIR = _REPO / "templates" / "authelia"


def test_authelia_config_dir_is_writable_not_ro() -> None:
    d = load_descriptors()["authelia"]
    assert "/etc/agmind/authelia:/config" in d.volumes, "config dir must be writable"
    assert not any(v.endswith(":/config:ro") for v in d.volumes), (
        "Authelia chowns + writes /config -> :ro causes EROFS crash"
    )
    # Persistent data on a separate mount so a config re-stage can't wipe the sqlite DB.
    assert "/var/lib/agmind/authelia:/data" in d.volumes


def test_authelia_secrets_wired_via_env() -> None:
    d = load_descriptors()["authelia"]
    env = d.env
    # Required secrets come from the runtime .env (generated by EnvWriteStep).
    assert "AUTHELIA_SESSION_SECRET" in env["AUTHELIA_SESSION_SECRET"]
    assert "AUTHELIA_STORAGE_ENCRYPTION_KEY" in env["AUTHELIA_STORAGE_ENCRYPTION_KEY"]
    assert (
        "AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET"
        in env["AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET"]
    )
    # Redis session store reuses the stack's REDIS_PASSWORD.
    assert "REDIS_PASSWORD" in env["AUTHELIA_SESSION_REDIS_PASSWORD"]


def test_authelia_config_template_minimal_valid() -> None:
    cfg = yaml.safe_load((_AUTH_DIR / "configuration.yml").read_text("utf-8"))
    assert cfg["authentication_backend"]["file"]["path"] == "/config/users_database.yml"
    assert cfg["access_control"]["default_policy"]
    assert cfg["session"]["cookies"][0]["domain"]
    # Persistent runtime data on /data (separate from the staged /config).
    assert cfg["storage"]["local"]["path"] == "/data/db.sqlite3"
    assert cfg["notifier"]["filesystem"]["filename"].startswith("/data/")
    # Secrets must NOT be hardcoded in the file (they come from env).
    raw = (_AUTH_DIR / "configuration.yml").read_text("utf-8")
    assert "encryption_key:" not in raw
    assert "secret:" not in raw


def test_authelia_users_db_has_admin_with_argon2() -> None:
    users = yaml.safe_load((_AUTH_DIR / "users_database.yml").read_text("utf-8"))["users"]
    assert "admin" in users
    assert users["admin"]["password"].startswith("$argon2id$")


def test_stage_authelia_substitutes_domain(tmp_path: Path) -> None:
    from agmind.install.steps import _stage_authelia_config

    target = tmp_path / "etc" / "authelia"
    _stage_authelia_config(_AUTH_DIR, target, domain="lab.example.com")

    cfg = yaml.safe_load((target / "configuration.yml").read_text("utf-8"))
    assert cfg["session"]["cookies"][0]["domain"] == "lab.example.com"
    assert cfg["session"]["cookies"][0]["authelia_url"] == "https://auth.lab.example.com"
    assert (target / "users_database.yml").exists()
    assert "__AGMIND_DOMAIN__" not in (target / "configuration.yml").read_text("utf-8")


def test_env_write_generates_authelia_secrets(tmp_path: Path) -> None:
    from agmind.core.env import parse_env_file
    from agmind.install.orchestrator import InstallConfig
    from agmind.install.steps import EnvWriteStep

    cfg = InstallConfig(
        domain="lab.example.com",
        cf_api_token="",
        services=["authelia", "redis"],
        install_dir=tmp_path / "opt",
        models_dir=tmp_path / "var" / "models",
        config_dir=tmp_path / "etc" / "agmind",
    )
    cfg.install_dir.mkdir(parents=True)
    assert EnvWriteStep().run(lambda _e: None, cfg).success
    env = parse_env_file(cfg.install_dir / ".env")
    for key in (
        "AUTHELIA_SESSION_SECRET",
        "AUTHELIA_STORAGE_ENCRYPTION_KEY",
        "AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET",
    ):
        assert env.get(key), f"{key} must be generated into .env"
        assert len(env[key]) >= 32
