from __future__ import annotations

import hashlib
import json
import shlex
import subprocess
import sys
from pathlib import Path

import pytest

from agmind.deploy.targets import DeploymentTarget

pytestmark = pytest.mark.backend_any

REPO_ROOT = Path(__file__).resolve().parents[1]


def _kubernetes_target(status: str = "research") -> DeploymentTarget:
    return DeploymentTarget.model_validate(
        {
            "id": f"k3s-{status}",
            "name": f"k3s {status}",
            "status": status,
            "summary": "Test Kubernetes target.",
            "runtime": {
                "kind": "kubernetes",
                "renderer": "agmind render kubernetes",
                "profiles": ["proxmox"],
            },
            "provisioner": {"kind": "external", "state_backend": "external"},
            "configurator": {
                "kind": "kubectl",
                "inventory_source": "kubeconfig",
                "manifests": ["k8s/agmind"],
            },
            "storage_profile": "longhorn",
            "secrets_profile": "external-secrets",
            "verification": {"commands": ["scripts/kubernetes_dry_run.py --require-cluster"]},
        }
    )


def test_kubernetes_dry_run_runs_kubectl_with_rendered_manifest() -> None:
    from agmind.services.kubernetes_dry_run import (
        CommandResult,
        run_kubernetes_server_dry_run,
    )

    calls: list[tuple[tuple[str, ...], str]] = []

    def fake_runner(command: tuple[str, ...], manifest: Path) -> CommandResult:
        calls.append((command, manifest.read_text(encoding="utf-8")))
        return CommandResult(returncode=0, stdout="server dry-run ok", stderr="")

    report = run_kubernetes_server_dry_run(
        {"k3s-research": _kubernetes_target()},
        kubectl="kubectl",
        runner=fake_runner,
    )

    assert report.ok is True
    assert report.targets[0].status == "passed"
    assert report.targets[0].returncode == 0
    assert report.targets[0].stdout == "server dry-run ok"
    assert calls
    command, manifest_text = calls[0]
    assert command[:4] == ("kubectl", "apply", "--dry-run=server", "-f")
    assert manifest_text.startswith("# Auto-generated by `agmind render kubernetes`")
    payload = report.to_json()
    assert payload["ok"] is True
    target_payload = payload["targets"][0]
    assert target_payload["target_id"] == "k3s-research"
    assert target_payload["status"] == "passed"
    assert target_payload["command"][:4] == ["kubectl", "apply", "--dry-run=server", "-f"]
    assert target_payload["warning_summary"] == {"info": 0, "warning": 0, "blocker": 0}
    assert target_payload["warnings"] == []
    assert target_payload["stdout"] == "server dry-run ok"
    assert target_payload["stderr"] == ""


def test_kubernetes_dry_run_skips_when_kubectl_is_missing() -> None:
    from agmind.services.kubernetes_dry_run import run_kubernetes_server_dry_run

    report = run_kubernetes_server_dry_run(
        {"k3s-research": _kubernetes_target()},
        kubectl=None,
    )

    assert report.ok is True
    assert report.targets[0].status == "skipped"
    assert report.targets[0].returncode is None
    assert "kubectl not found" in report.targets[0].stderr


def test_kubernetes_dry_run_requires_cluster_when_requested() -> None:
    from agmind.services.kubernetes_dry_run import run_kubernetes_server_dry_run

    report = run_kubernetes_server_dry_run(
        {"k3s-research": _kubernetes_target()},
        kubectl=None,
        require_cluster=True,
    )

    assert report.ok is False
    assert report.targets[0].status == "skipped"
    assert "kubectl not found" in report.targets[0].stderr


def test_kubernetes_dry_run_reports_kubectl_failure() -> None:
    from agmind.services.kubernetes_dry_run import (
        CommandResult,
        run_kubernetes_server_dry_run,
    )

    def fake_runner(command: tuple[str, ...], manifest: Path) -> CommandResult:
        return CommandResult(returncode=1, stdout="", stderr="namespace agmind not found")

    report = run_kubernetes_server_dry_run(
        {"k3s-research": _kubernetes_target()},
        kubectl="kubectl",
        runner=fake_runner,
    )

    assert report.ok is False
    assert report.targets[0].status == "failed"
    assert report.targets[0].returncode == 1
    assert "namespace agmind not found" in report.targets[0].stderr


def test_kubernetes_dry_run_writes_artifact_files(tmp_path: Path) -> None:
    from agmind.services.kubernetes_dry_run import (
        CommandResult,
        run_kubernetes_server_dry_run,
    )

    commands: list[tuple[str, ...]] = []

    def fake_runner(command: tuple[str, ...], manifest: Path) -> CommandResult:
        commands.append(command)
        assert manifest == tmp_path / "k3s-research.yaml"
        return CommandResult(returncode=0, stdout="server dry-run ok", stderr="")

    report = run_kubernetes_server_dry_run(
        {"k3s-research": _kubernetes_target()},
        kubectl="kubectl",
        runner=fake_runner,
        artifact_dir=tmp_path,
    )

    manifest = tmp_path / "k3s-research.yaml"
    target_report = tmp_path / "k3s-research.dry-run.json"
    summary = tmp_path / "summary.json"

    assert report.ok is True
    assert manifest.exists()
    assert target_report.exists()
    assert summary.exists()
    assert commands[0][-1] == str(manifest)
    assert report.targets[0].manifest_path == manifest
    assert report.targets[0].report_path == target_report
    assert json.loads(target_report.read_text(encoding="utf-8"))["target_id"] == "k3s-research"
    assert json.loads(summary.read_text(encoding="utf-8"))["targets"][0]["target_id"] == (
        "k3s-research"
    )


def test_kubernetes_dry_run_artifact_records_manifest_digest_and_checksums(
    tmp_path: Path,
) -> None:
    from agmind.services.kubernetes_dry_run import (
        CommandResult,
        run_kubernetes_server_dry_run,
    )

    def fake_runner(command: tuple[str, ...], manifest: Path) -> CommandResult:
        return CommandResult(returncode=0, stdout="server dry-run ok", stderr="")

    report = run_kubernetes_server_dry_run(
        {"k3s-research": _kubernetes_target()},
        kubectl="kubectl",
        runner=fake_runner,
        artifact_dir=tmp_path,
    )

    manifest = tmp_path / "k3s-research.yaml"
    target_report = tmp_path / "k3s-research.dry-run.json"
    summary = tmp_path / "summary.json"
    checksums = tmp_path / "checksums.txt"
    manifest_bytes = manifest.read_bytes()
    summary_bytes = summary.read_bytes()
    target_report_bytes = target_report.read_bytes()

    assert report.ok is True
    assert checksums.exists()
    target_payload = json.loads(target_report_bytes)
    summary_payload = json.loads(summary_bytes)
    assert target_payload["manifest_bytes"] == len(manifest_bytes)
    assert target_payload["manifest_sha256"] == hashlib.sha256(manifest_bytes).hexdigest()
    assert summary_payload["checksum_path"] == str(checksums)
    checksum_lines = checksums.read_text(encoding="utf-8").splitlines()
    assert f"{hashlib.sha256(manifest_bytes).hexdigest()}  k3s-research.yaml" in checksum_lines
    assert (
        f"{hashlib.sha256(target_report_bytes).hexdigest()}  k3s-research.dry-run.json"
        in checksum_lines
    )
    assert f"{hashlib.sha256(summary_bytes).hexdigest()}  summary.json" in checksum_lines
    assert not any(line.endswith("checksums.txt") for line in checksum_lines)


def test_kubernetes_dry_run_artifact_records_proof_command(tmp_path: Path) -> None:
    from agmind.services.kubernetes_dry_run import (
        CommandResult,
        run_kubernetes_server_dry_run,
    )

    def fake_runner(command: tuple[str, ...], manifest: Path) -> CommandResult:
        if command[-4:] == ("get", "nodes", "-o", "json"):
            return CommandResult(
                returncode=0,
                stdout=json.dumps(
                    {
                        "items": [
                            {
                                "metadata": {"name": "strix"},
                                "status": {"allocatable": {"amd.com/gpu": "1"}},
                            }
                        ]
                    }
                ),
                stderr="",
            )
        return CommandResult(returncode=0, stdout="server dry-run ok", stderr="")

    report = run_kubernetes_server_dry_run(
        {"k3s-research": _kubernetes_target()},
        kubectl="kubectl",
        kube_context="strix-k3s",
        namespace="agmind-ci",
        require_cluster=True,
        require_amd_gpu=True,
        target_ids=("k3s-research",),
        runner=fake_runner,
        artifact_dir=tmp_path,
    )

    proof_command = tmp_path / "proof-command.txt"
    expected_command = [
        "scripts/kubernetes_dry_run.py",
        "--target",
        "k3s-research",
        "--require-cluster",
        "--require-amd-gpu",
        "--artifact-dir",
        str(tmp_path),
        "--namespace",
        "agmind-ci",
        "--kubectl",
        "kubectl",
        "--context",
        "strix-k3s",
    ]
    summary_payload = json.loads((tmp_path / "summary.json").read_text(encoding="utf-8"))
    proof_command_bytes = proof_command.read_bytes()
    checksum_lines = (tmp_path / "checksums.txt").read_text(encoding="utf-8").splitlines()

    assert report.ok is True
    assert proof_command.read_text(encoding="utf-8").strip() == " ".join(expected_command)
    assert summary_payload["proof_command"] == expected_command
    assert summary_payload["proof_command_path"] == str(proof_command)
    assert f"{hashlib.sha256(proof_command_bytes).hexdigest()}  proof-command.txt" in checksum_lines


def test_kubernetes_dry_run_artifact_records_run_metadata(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    from agmind.services.kubernetes_dry_run import (
        CommandResult,
        run_kubernetes_server_dry_run,
        verify_kubernetes_dry_run_artifacts,
    )

    monkeypatch.setenv("GITHUB_ACTIONS", "true")
    monkeypatch.setenv("GITHUB_WORKFLOW", "Kubernetes Proof")
    monkeypatch.setenv("GITHUB_RUN_ID", "12345")
    monkeypatch.setenv("GITHUB_SHA", "abc123")
    monkeypatch.setenv("RUNNER_NAME", "strix-k3s")
    monkeypatch.setenv("RUNNER_OS", "Linux")
    monkeypatch.setenv("RUNNER_ARCH", "X64")

    def fake_runner(command: tuple[str, ...], manifest: Path) -> CommandResult:
        return CommandResult(returncode=0, stdout="server dry-run ok", stderr="")

    run_kubernetes_server_dry_run(
        {"k3s-research": _kubernetes_target()},
        kubectl="kubectl",
        runner=fake_runner,
        artifact_dir=tmp_path,
    )

    metadata_path = tmp_path / "run-metadata.json"
    summary_payload = json.loads((tmp_path / "summary.json").read_text(encoding="utf-8"))
    metadata_payload = json.loads(metadata_path.read_text(encoding="utf-8"))
    checksum_lines = (tmp_path / "checksums.txt").read_text(encoding="utf-8").splitlines()

    assert metadata_path.exists()
    assert summary_payload["run_metadata_path"] == str(metadata_path)
    assert summary_payload["run_metadata"] == metadata_payload
    assert metadata_payload["source"] == "github-actions"
    assert metadata_payload["github_workflow"] == "Kubernetes Proof"
    assert metadata_payload["github_run_id"] == "12345"
    assert metadata_payload["github_sha"] == "abc123"
    assert metadata_payload["runner_name"] == "strix-k3s"
    assert any(line.endswith("  run-metadata.json") for line in checksum_lines)
    assert verify_kubernetes_dry_run_artifacts(tmp_path).ok is True


def test_kubernetes_dry_run_artifact_verifier_accepts_valid_bundle(tmp_path: Path) -> None:
    from agmind.services.kubernetes_dry_run import (
        CommandResult,
        run_kubernetes_server_dry_run,
        verify_kubernetes_dry_run_artifacts,
    )

    def fake_runner(command: tuple[str, ...], manifest: Path) -> CommandResult:
        return CommandResult(returncode=0, stdout="server dry-run ok", stderr="")

    run_kubernetes_server_dry_run(
        {"k3s-research": _kubernetes_target()},
        kubectl="kubectl",
        runner=fake_runner,
        artifact_dir=tmp_path,
    )

    report = verify_kubernetes_dry_run_artifacts(tmp_path)

    assert report.ok is True
    payload = report.to_json()
    assert payload["artifact_dir"] == str(tmp_path)
    assert payload["summary_path"] == str(tmp_path / "summary.json")
    assert payload["checksum_path"] == str(tmp_path / "checksums.txt")
    assert {item["path"] for item in payload["files"]} == {
        "k3s-research.dry-run.json",
        "k3s-research.yaml",
        "proof-command.txt",
        "run-metadata.json",
        "summary.json",
    }
    assert all(item["ok"] is True for item in payload["files"])
    assert payload["errors"] == []


def test_kubernetes_dry_run_artifact_verifier_rejects_corrupt_manifest(
    tmp_path: Path,
) -> None:
    from agmind.services.kubernetes_dry_run import (
        CommandResult,
        run_kubernetes_server_dry_run,
        verify_kubernetes_dry_run_artifacts,
    )

    def fake_runner(command: tuple[str, ...], manifest: Path) -> CommandResult:
        return CommandResult(returncode=0, stdout="server dry-run ok", stderr="")

    run_kubernetes_server_dry_run(
        {"k3s-research": _kubernetes_target()},
        kubectl="kubectl",
        runner=fake_runner,
        artifact_dir=tmp_path,
    )
    (tmp_path / "k3s-research.yaml").write_text("corrupt\n", encoding="utf-8")

    report = verify_kubernetes_dry_run_artifacts(tmp_path)

    assert report.ok is False
    payload = report.to_json()
    assert any(
        item["path"] == "k3s-research.yaml" and item["ok"] is False for item in payload["files"]
    )
    assert any("checksum mismatch: k3s-research.yaml" in error for error in payload["errors"])
    assert any("manifest_sha256 mismatch" in error for error in payload["errors"])


def test_kubernetes_dry_run_artifact_verifier_rejects_corrupt_proof_command(
    tmp_path: Path,
) -> None:
    from agmind.services.kubernetes_dry_run import (
        CommandResult,
        run_kubernetes_server_dry_run,
        verify_kubernetes_dry_run_artifacts,
    )

    def fake_runner(command: tuple[str, ...], manifest: Path) -> CommandResult:
        return CommandResult(returncode=0, stdout="server dry-run ok", stderr="")

    run_kubernetes_server_dry_run(
        {"k3s-research": _kubernetes_target()},
        kubectl="kubectl",
        runner=fake_runner,
        artifact_dir=tmp_path,
    )
    (tmp_path / "proof-command.txt").write_text("corrupt\n", encoding="utf-8")

    report = verify_kubernetes_dry_run_artifacts(tmp_path)

    assert report.ok is False
    payload = report.to_json()
    assert any(
        item["path"] == "proof-command.txt" and item["ok"] is False for item in payload["files"]
    )
    assert any("checksum mismatch: proof-command.txt" in error for error in payload["errors"])


def test_kubernetes_dry_run_artifact_verifier_rejects_proof_command_summary_mismatch(
    tmp_path: Path,
) -> None:
    from agmind.services.kubernetes_dry_run import (
        CommandResult,
        run_kubernetes_server_dry_run,
        verify_kubernetes_dry_run_artifacts,
    )

    def fake_runner(command: tuple[str, ...], manifest: Path) -> CommandResult:
        return CommandResult(returncode=0, stdout="server dry-run ok", stderr="")

    run_kubernetes_server_dry_run(
        {"k3s-research": _kubernetes_target()},
        kubectl="kubectl",
        runner=fake_runner,
        artifact_dir=tmp_path,
    )
    proof_command = tmp_path / "proof-command.txt"
    proof_command.write_text(
        "python scripts/kubernetes_dry_run.py --target other\n",
        encoding="utf-8",
    )
    proof_digest = hashlib.sha256(proof_command.read_bytes()).hexdigest()
    checksums = tmp_path / "checksums.txt"
    checksums.write_text(
        "\n".join(
            f"{proof_digest}  proof-command.txt" if line.endswith("  proof-command.txt") else line
            for line in checksums.read_text(encoding="utf-8").splitlines()
        )
        + "\n",
        encoding="utf-8",
    )

    report = verify_kubernetes_dry_run_artifacts(tmp_path)

    assert report.ok is False
    assert "proof-command.txt does not match summary.json proof_command" in report.errors


def test_kubernetes_dry_run_artifact_verifier_rejects_target_report_summary_mismatch(
    tmp_path: Path,
) -> None:
    from agmind.services.kubernetes_dry_run import (
        CommandResult,
        run_kubernetes_server_dry_run,
        verify_kubernetes_dry_run_artifacts,
    )

    def fake_runner(command: tuple[str, ...], manifest: Path) -> CommandResult:
        return CommandResult(returncode=0, stdout="server dry-run ok", stderr="")

    run_kubernetes_server_dry_run(
        {"k3s-research": _kubernetes_target()},
        kubectl="kubectl",
        runner=fake_runner,
        artifact_dir=tmp_path,
    )
    target_report = tmp_path / "k3s-research.dry-run.json"
    target_payload = json.loads(target_report.read_text(encoding="utf-8"))
    target_payload["status"] = "failed"
    target_report.write_text(json.dumps(target_payload, indent=2) + "\n", encoding="utf-8")
    target_digest = hashlib.sha256(target_report.read_bytes()).hexdigest()
    checksums = tmp_path / "checksums.txt"
    checksums.write_text(
        "\n".join(
            f"{target_digest}  k3s-research.dry-run.json"
            if line.endswith("  k3s-research.dry-run.json")
            else line
            for line in checksums.read_text(encoding="utf-8").splitlines()
        )
        + "\n",
        encoding="utf-8",
    )

    report = verify_kubernetes_dry_run_artifacts(tmp_path)

    assert report.ok is False
    assert (
        "k3s-research: target report artifact does not match summary.json target" in report.errors
    )


def test_kubernetes_dry_run_artifact_verifier_rejects_summary_ok_mismatch(
    tmp_path: Path,
) -> None:
    from agmind.services.kubernetes_dry_run import (
        CommandResult,
        run_kubernetes_server_dry_run,
        verify_kubernetes_dry_run_artifacts,
    )

    def fake_runner(command: tuple[str, ...], manifest: Path) -> CommandResult:
        return CommandResult(returncode=0, stdout="server dry-run ok", stderr="")

    run_kubernetes_server_dry_run(
        {"k3s-research": _kubernetes_target()},
        kubectl="kubectl",
        runner=fake_runner,
        artifact_dir=tmp_path,
    )
    summary = tmp_path / "summary.json"
    summary_payload = json.loads(summary.read_text(encoding="utf-8"))
    summary_payload["ok"] = False
    summary.write_text(json.dumps(summary_payload, indent=2) + "\n", encoding="utf-8")
    summary_digest = hashlib.sha256(summary.read_bytes()).hexdigest()
    checksums = tmp_path / "checksums.txt"
    checksums.write_text(
        "\n".join(
            f"{summary_digest}  summary.json" if line.endswith("  summary.json") else line
            for line in checksums.read_text(encoding="utf-8").splitlines()
        )
        + "\n",
        encoding="utf-8",
    )

    report = verify_kubernetes_dry_run_artifacts(tmp_path)

    assert report.ok is False
    assert "summary.json ok does not match target statuses" in report.errors


def test_kubernetes_dry_run_artifact_verifier_rejects_target_ids_mismatch(
    tmp_path: Path,
) -> None:
    from agmind.services.kubernetes_dry_run import (
        CommandResult,
        run_kubernetes_server_dry_run,
        verify_kubernetes_dry_run_artifacts,
    )

    def fake_runner(command: tuple[str, ...], manifest: Path) -> CommandResult:
        return CommandResult(returncode=0, stdout="server dry-run ok", stderr="")

    run_kubernetes_server_dry_run(
        {"k3s-research": _kubernetes_target()},
        kubectl="kubectl",
        runner=fake_runner,
        artifact_dir=tmp_path,
    )
    summary = tmp_path / "summary.json"
    summary_payload = json.loads(summary.read_text(encoding="utf-8"))
    summary_payload["target_ids"] = ["other"]
    summary.write_text(json.dumps(summary_payload, indent=2) + "\n", encoding="utf-8")
    summary_digest = hashlib.sha256(summary.read_bytes()).hexdigest()
    checksums = tmp_path / "checksums.txt"
    checksums.write_text(
        "\n".join(
            f"{summary_digest}  summary.json" if line.endswith("  summary.json") else line
            for line in checksums.read_text(encoding="utf-8").splitlines()
        )
        + "\n",
        encoding="utf-8",
    )

    report = verify_kubernetes_dry_run_artifacts(tmp_path)

    assert report.ok is False
    assert "summary.json target_ids do not match target records" in report.errors


def test_kubernetes_dry_run_artifact_verifier_rejects_proof_command_target_mismatch(
    tmp_path: Path,
) -> None:
    from agmind.services.kubernetes_dry_run import (
        CommandResult,
        run_kubernetes_server_dry_run,
        verify_kubernetes_dry_run_artifacts,
    )

    def fake_runner(command: tuple[str, ...], manifest: Path) -> CommandResult:
        return CommandResult(returncode=0, stdout="server dry-run ok", stderr="")

    run_kubernetes_server_dry_run(
        {"k3s-research": _kubernetes_target()},
        kubectl="kubectl",
        runner=fake_runner,
        artifact_dir=tmp_path,
    )
    summary = tmp_path / "summary.json"
    summary_payload = json.loads(summary.read_text(encoding="utf-8"))
    proof_command = list(summary_payload["proof_command"])
    proof_command[proof_command.index("--target") + 1] = "other"
    summary_payload["proof_command"] = proof_command
    summary.write_text(json.dumps(summary_payload, indent=2) + "\n", encoding="utf-8")
    proof_command_artifact = tmp_path / "proof-command.txt"
    proof_command_artifact.write_text(shlex.join(proof_command) + "\n", encoding="utf-8")

    summary_digest = hashlib.sha256(summary.read_bytes()).hexdigest()
    proof_digest = hashlib.sha256(proof_command_artifact.read_bytes()).hexdigest()
    checksums = tmp_path / "checksums.txt"
    checksums.write_text(
        "\n".join(
            f"{summary_digest}  summary.json"
            if line.endswith("  summary.json")
            else f"{proof_digest}  proof-command.txt"
            if line.endswith("  proof-command.txt")
            else line
            for line in checksums.read_text(encoding="utf-8").splitlines()
        )
        + "\n",
        encoding="utf-8",
    )

    report = verify_kubernetes_dry_run_artifacts(tmp_path)

    assert report.ok is False
    assert "summary.json proof_command targets do not match target_ids" in report.errors


def test_kubernetes_dry_run_artifact_verifier_rejects_missing_require_cluster_flag(
    tmp_path: Path,
) -> None:
    from agmind.services.kubernetes_dry_run import (
        CommandResult,
        run_kubernetes_server_dry_run,
        verify_kubernetes_dry_run_artifacts,
    )

    def fake_runner(command: tuple[str, ...], manifest: Path) -> CommandResult:
        return CommandResult(returncode=0, stdout="server dry-run ok", stderr="")

    run_kubernetes_server_dry_run(
        {"k3s-research": _kubernetes_target()},
        kubectl="kubectl",
        require_cluster=True,
        runner=fake_runner,
        artifact_dir=tmp_path,
    )
    summary = tmp_path / "summary.json"
    summary_payload = json.loads(summary.read_text(encoding="utf-8"))
    proof_command = [
        part for part in summary_payload["proof_command"] if part != "--require-cluster"
    ]
    summary_payload["proof_command"] = proof_command
    summary.write_text(json.dumps(summary_payload, indent=2) + "\n", encoding="utf-8")
    proof_command_artifact = tmp_path / "proof-command.txt"
    proof_command_artifact.write_text(shlex.join(proof_command) + "\n", encoding="utf-8")

    summary_digest = hashlib.sha256(summary.read_bytes()).hexdigest()
    proof_digest = hashlib.sha256(proof_command_artifact.read_bytes()).hexdigest()
    checksums = tmp_path / "checksums.txt"
    checksums.write_text(
        "\n".join(
            f"{summary_digest}  summary.json"
            if line.endswith("  summary.json")
            else f"{proof_digest}  proof-command.txt"
            if line.endswith("  proof-command.txt")
            else line
            for line in checksums.read_text(encoding="utf-8").splitlines()
        )
        + "\n",
        encoding="utf-8",
    )

    report = verify_kubernetes_dry_run_artifacts(tmp_path)

    assert report.ok is False
    assert "summary.json proof_command require_cluster flag does not match summary" in report.errors


def test_kubernetes_dry_run_artifact_verifier_rejects_missing_required_checksum(
    tmp_path: Path,
) -> None:
    from agmind.services.kubernetes_dry_run import (
        CommandResult,
        run_kubernetes_server_dry_run,
        verify_kubernetes_dry_run_artifacts,
    )

    def fake_runner(command: tuple[str, ...], manifest: Path) -> CommandResult:
        return CommandResult(returncode=0, stdout="server dry-run ok", stderr="")

    run_kubernetes_server_dry_run(
        {"k3s-research": _kubernetes_target()},
        kubectl="kubectl",
        runner=fake_runner,
        artifact_dir=tmp_path,
    )
    checksums = tmp_path / "checksums.txt"
    checksums.write_text(
        "\n".join(
            line
            for line in checksums.read_text(encoding="utf-8").splitlines()
            if not line.endswith("  run-metadata.json")
        )
        + "\n",
        encoding="utf-8",
    )

    report = verify_kubernetes_dry_run_artifacts(tmp_path)

    assert report.ok is False
    assert "missing checksum entry for required artifact: run-metadata.json" in report.errors


def test_kubernetes_dry_run_artifact_verifier_rejects_missing_required_artifact(
    tmp_path: Path,
) -> None:
    from agmind.services.kubernetes_dry_run import (
        CommandResult,
        run_kubernetes_server_dry_run,
        verify_kubernetes_dry_run_artifacts,
    )

    def fake_runner(command: tuple[str, ...], manifest: Path) -> CommandResult:
        return CommandResult(returncode=0, stdout="server dry-run ok", stderr="")

    run_kubernetes_server_dry_run(
        {"k3s-research": _kubernetes_target()},
        kubectl="kubectl",
        runner=fake_runner,
        artifact_dir=tmp_path,
    )
    (tmp_path / "proof-command.txt").unlink()
    checksums = tmp_path / "checksums.txt"
    checksums.write_text(
        "\n".join(
            line
            for line in checksums.read_text(encoding="utf-8").splitlines()
            if not line.endswith("  proof-command.txt")
        )
        + "\n",
        encoding="utf-8",
    )

    report = verify_kubernetes_dry_run_artifacts(tmp_path)

    assert report.ok is False
    assert "missing required artifact: proof-command.txt" in report.errors


def test_kubernetes_dry_run_artifact_verifier_rejects_checksum_path_escape(
    tmp_path: Path,
) -> None:
    from agmind.services.kubernetes_dry_run import (
        CommandResult,
        run_kubernetes_server_dry_run,
        verify_kubernetes_dry_run_artifacts,
    )

    def fake_runner(command: tuple[str, ...], manifest: Path) -> CommandResult:
        return CommandResult(returncode=0, stdout="server dry-run ok", stderr="")

    run_kubernetes_server_dry_run(
        {"k3s-research": _kubernetes_target()},
        kubectl="kubectl",
        runner=fake_runner,
        artifact_dir=tmp_path,
    )
    outside = tmp_path.parent / "outside-proof-file.txt"
    outside.write_text("outside\n", encoding="utf-8")
    outside_digest = hashlib.sha256(outside.read_bytes()).hexdigest()
    checksums = tmp_path / "checksums.txt"
    checksums.write_text(
        checksums.read_text(encoding="utf-8") + f"{outside_digest}  ../{outside.name}\n",
        encoding="utf-8",
    )

    report = verify_kubernetes_dry_run_artifacts(tmp_path)

    assert report.ok is False
    assert any(
        "checksum path escapes artifact directory: ../outside-proof-file.txt" in error
        for error in report.errors
    )


def test_kubernetes_dry_run_summary_records_invocation_metadata(tmp_path: Path) -> None:
    from agmind.services.kubernetes_dry_run import (
        CommandResult,
        run_kubernetes_server_dry_run,
    )

    def fake_runner(command: tuple[str, ...], manifest: Path) -> CommandResult:
        if command[-4:] == ("get", "nodes", "-o", "json"):
            return CommandResult(
                returncode=0,
                stdout=json.dumps(
                    {
                        "items": [
                            {
                                "metadata": {"name": "strix"},
                                "status": {"allocatable": {"amd.com/gpu": "1"}},
                            }
                        ]
                    }
                ),
                stderr="",
            )
        return CommandResult(returncode=0, stdout="server dry-run ok", stderr="")

    report = run_kubernetes_server_dry_run(
        {"k3s-research": _kubernetes_target()},
        kubectl="kubectl",
        kube_context="strix-k3s",
        namespace="agmind-ci",
        require_cluster=True,
        require_amd_gpu=True,
        runner=fake_runner,
        artifact_dir=tmp_path,
    )

    payload = json.loads((tmp_path / "summary.json").read_text(encoding="utf-8"))

    assert report.ok is True
    assert payload["kubectl"] == "kubectl"
    assert payload["kube_context"] == "strix-k3s"
    assert payload["namespace"] == "agmind-ci"
    assert payload["require_cluster"] is True
    assert payload["require_amd_gpu"] is True
    assert payload["artifact_dir"] == str(tmp_path)
    assert payload["summary_path"] == str(tmp_path / "summary.json")
    assert payload["targets"][0]["manifest_path"] == str(tmp_path / "k3s-research.yaml")
    assert payload["targets"][0]["gpu_preflight"]["allocatable"] == 1


def test_kubernetes_dry_run_runs_only_selected_target(tmp_path: Path) -> None:
    from agmind.services.kubernetes_dry_run import (
        CommandResult,
        run_kubernetes_server_dry_run,
    )

    calls: list[tuple[str, ...]] = []

    def fake_runner(command: tuple[str, ...], manifest: Path) -> CommandResult:
        calls.append(command)
        return CommandResult(returncode=0, stdout="server dry-run ok", stderr="")

    report = run_kubernetes_server_dry_run(
        {
            "k3s-research": _kubernetes_target("research"),
            "k3s-experimental": _kubernetes_target("experimental"),
        },
        kubectl="kubectl",
        runner=fake_runner,
        artifact_dir=tmp_path,
        target_ids=("k3s-experimental",),
    )

    payload = json.loads((tmp_path / "summary.json").read_text(encoding="utf-8"))

    assert report.ok is True
    assert [target.target_id for target in report.targets] == ["k3s-experimental"]
    assert payload["target_ids"] == ["k3s-experimental"]
    assert (tmp_path / "k3s-experimental.yaml").exists()
    assert not (tmp_path / "k3s-research.yaml").exists()
    assert len(calls) == 1


def test_kubernetes_dry_run_rejects_unknown_selected_target() -> None:
    from agmind.services.kubernetes_dry_run import run_kubernetes_server_dry_run

    with pytest.raises(ValueError, match="unknown deployment target"):
        run_kubernetes_server_dry_run(
            {"k3s-research": _kubernetes_target()},
            target_ids=("missing",),
        )


def test_kubernetes_dry_run_requires_amd_gpu_preflight() -> None:
    from agmind.services.kubernetes_dry_run import (
        CommandResult,
        format_kubernetes_dry_run_report,
        run_kubernetes_server_dry_run,
    )

    calls: list[tuple[str, ...]] = []

    def fake_runner(command: tuple[str, ...], manifest: Path) -> CommandResult:
        calls.append(command)
        if command[-4:] == ("get", "nodes", "-o", "json"):
            return CommandResult(
                returncode=0,
                stdout=json.dumps(
                    {
                        "items": [
                            {
                                "metadata": {"name": "strix"},
                                "status": {"allocatable": {"amd.com/gpu": "1"}},
                            }
                        ]
                    }
                ),
                stderr="",
            )
        return CommandResult(returncode=0, stdout="server dry-run ok", stderr="")

    report = run_kubernetes_server_dry_run(
        {"k3s-research": _kubernetes_target()},
        kubectl="kubectl",
        runner=fake_runner,
        require_amd_gpu=True,
    )

    assert report.ok is True
    assert report.targets[0].status == "passed"
    assert report.targets[0].gpu_preflight is not None
    assert report.targets[0].gpu_preflight.status == "passed"
    assert report.targets[0].gpu_preflight.allocatable == 1
    assert calls[0] == ("kubectl", "get", "nodes", "-o", "json")
    assert calls[1][:4] == ("kubectl", "apply", "--dry-run=server", "-f")
    payload = report.to_json()["targets"][0]
    assert payload["gpu_preflight"]["resource_name"] == "amd.com/gpu"
    assert payload["gpu_preflight"]["allocatable"] == 1
    rendered = format_kubernetes_dry_run_report(report)
    assert "gpu preflight: PASSED" in rendered
    assert "amd.com/gpu=1" in rendered


def test_kubernetes_dry_run_fails_when_required_amd_gpu_is_not_allocatable() -> None:
    from agmind.services.kubernetes_dry_run import (
        CommandResult,
        run_kubernetes_server_dry_run,
    )

    calls: list[tuple[str, ...]] = []

    def fake_runner(command: tuple[str, ...], manifest: Path) -> CommandResult:
        calls.append(command)
        return CommandResult(
            returncode=0,
            stdout=json.dumps(
                {
                    "items": [
                        {"metadata": {"name": "cpu-node"}, "status": {"allocatable": {"cpu": "16"}}}
                    ]
                }
            ),
            stderr="",
        )

    report = run_kubernetes_server_dry_run(
        {"k3s-research": _kubernetes_target()},
        kubectl="kubectl",
        runner=fake_runner,
        require_amd_gpu=True,
    )

    assert report.ok is False
    assert report.targets[0].status == "failed"
    assert report.targets[0].gpu_preflight is not None
    assert report.targets[0].gpu_preflight.status == "failed"
    assert report.targets[0].gpu_preflight.allocatable == 0
    assert "amd.com/gpu" in report.targets[0].stderr
    assert calls == [("kubectl", "get", "nodes", "-o", "json")]


def test_kubernetes_dry_run_artifact_records_amd_gpu_preflight(tmp_path: Path) -> None:
    from agmind.services.kubernetes_dry_run import (
        CommandResult,
        run_kubernetes_server_dry_run,
    )

    def fake_runner(command: tuple[str, ...], manifest: Path) -> CommandResult:
        if command[-4:] == ("get", "nodes", "-o", "json"):
            return CommandResult(
                returncode=0,
                stdout=json.dumps(
                    {
                        "items": [
                            {
                                "metadata": {"name": "strix"},
                                "status": {"allocatable": {"amd.com/gpu": "2"}},
                            }
                        ]
                    }
                ),
                stderr="",
            )
        return CommandResult(returncode=0, stdout="server dry-run ok", stderr="")

    report = run_kubernetes_server_dry_run(
        {"k3s-research": _kubernetes_target()},
        kubectl="kubectl",
        runner=fake_runner,
        require_amd_gpu=True,
        artifact_dir=tmp_path,
    )

    target_payload = json.loads(
        (tmp_path / "k3s-research.dry-run.json").read_text(encoding="utf-8")
    )
    summary_payload = json.loads((tmp_path / "summary.json").read_text(encoding="utf-8"))

    assert report.ok is True
    assert target_payload["gpu_preflight"]["status"] == "passed"
    assert target_payload["gpu_preflight"]["allocatable"] == 2
    assert summary_payload["targets"][0]["gpu_preflight"]["allocatable"] == 2


def test_kubernetes_dry_run_script_json_skips_without_cluster() -> None:
    result = subprocess.run(
        [sys.executable, str(REPO_ROOT / "scripts" / "kubernetes_dry_run.py"), "--json"],
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr + result.stdout
    payload = json.loads(result.stdout)
    assert payload["ok"] is True
    assert payload["targets"][0]["target_id"] == "k3s"
    assert payload["targets"][0]["status"] in {"passed", "skipped"}


def test_kubernetes_dry_run_script_require_cluster_fails_without_kubectl() -> None:
    result = subprocess.run(
        [
            sys.executable,
            str(REPO_ROOT / "scripts" / "kubernetes_dry_run.py"),
            "--require-cluster",
            "--kubectl",
            "/definitely/missing/kubectl",
        ],
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 1
    assert "kubectl not found" in result.stdout


def test_kubernetes_dry_run_script_accepts_require_amd_gpu_flag_without_cluster() -> None:
    result = subprocess.run(
        [
            sys.executable,
            str(REPO_ROOT / "scripts" / "kubernetes_dry_run.py"),
            "--json",
            "--require-amd-gpu",
            "--kubectl",
            "/definitely/missing/kubectl",
        ],
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr + result.stdout
    payload = json.loads(result.stdout)
    assert payload["targets"][0]["status"] == "skipped"
    assert payload["targets"][0]["gpu_preflight"]["status"] == "skipped"
    assert "kubectl not found" in payload["targets"][0]["gpu_preflight"]["stderr"]
    assert payload["kubectl"] == "/definitely/missing/kubectl"
    assert payload["require_amd_gpu"] is True


def test_kubernetes_dry_run_script_writes_artifacts(tmp_path: Path) -> None:
    result = subprocess.run(
        [
            sys.executable,
            str(REPO_ROOT / "scripts" / "kubernetes_dry_run.py"),
            "--json",
            "--artifact-dir",
            str(tmp_path),
        ],
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr + result.stdout
    assert (tmp_path / "k3s.yaml").exists()
    assert (tmp_path / "k3s.dry-run.json").exists()
    assert (tmp_path / "summary.json").exists()
    payload = json.loads(result.stdout)
    assert payload["targets"][0]["report_path"] == str(tmp_path / "k3s.dry-run.json")
    summary_payload = json.loads((tmp_path / "summary.json").read_text(encoding="utf-8"))
    assert summary_payload["artifact_dir"] == str(tmp_path)
    assert summary_payload["summary_path"] == str(tmp_path / "summary.json")


def test_kubernetes_dry_run_script_accepts_target_selection(tmp_path: Path) -> None:
    result = subprocess.run(
        [
            sys.executable,
            str(REPO_ROOT / "scripts" / "kubernetes_dry_run.py"),
            "--json",
            "--target",
            "k3s",
            "--artifact-dir",
            str(tmp_path),
        ],
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr + result.stdout
    payload = json.loads(result.stdout)
    assert payload["target_ids"] == ["k3s"]
    assert [target["target_id"] for target in payload["targets"]] == ["k3s"]
    assert (tmp_path / "k3s.yaml").exists()


def test_kubernetes_dry_run_artifact_records_render_warning_details(tmp_path: Path) -> None:
    result = subprocess.run(
        [
            sys.executable,
            str(REPO_ROOT / "scripts" / "kubernetes_dry_run.py"),
            "--json",
            "--target",
            "k3s",
            "--artifact-dir",
            str(tmp_path),
        ],
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr + result.stdout
    target_payload = json.loads((tmp_path / "k3s.dry-run.json").read_text(encoding="utf-8"))
    summary_payload = json.loads((tmp_path / "summary.json").read_text(encoding="utf-8"))

    assert target_payload["warning_summary"]["warning"] == 4
    assert len(target_payload["warnings"]) == 4
    assert summary_payload["targets"][0]["warnings"] == target_payload["warnings"]
    assert all(
        set(item) == {"service", "code", "severity", "message", "remediation", "expected"}
        for item in target_payload["warnings"]
    )
    assert all(item["expected"] is True for item in target_payload["warnings"])
    assert any(
        item["code"] == "amd-gpu-device-plugin" and item["expected"] is True
        for item in target_payload["warnings"]
    )
    assert any(
        item["code"] == "kubernetes-omitted"
        and item["service"] == "llama-rerank"
        and "rerank model file" in item["message"]
        and item["expected"] is True
        for item in target_payload["warnings"]
    )
    assert not any(item["code"] == "command-interpolation" for item in target_payload["warnings"])


def test_kubernetes_dry_run_script_rejects_unknown_target() -> None:
    result = subprocess.run(
        [
            sys.executable,
            str(REPO_ROOT / "scripts" / "kubernetes_dry_run.py"),
            "--target",
            "missing-target",
        ],
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 2
    assert "unknown deployment target" in result.stderr


def test_kubernetes_dry_run_script_verifies_artifact_bundle(tmp_path: Path) -> None:
    build_result = subprocess.run(
        [
            sys.executable,
            str(REPO_ROOT / "scripts" / "kubernetes_dry_run.py"),
            "--json",
            "--target",
            "k3s",
            "--artifact-dir",
            str(tmp_path),
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    assert build_result.returncode == 0, build_result.stderr + build_result.stdout

    result = subprocess.run(
        [
            sys.executable,
            str(REPO_ROOT / "scripts" / "kubernetes_dry_run.py"),
            "--verify-artifact-dir",
            str(tmp_path),
        ],
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr + result.stdout
    assert "kubernetes dry-run artifact bundle OK" in result.stdout


def test_kubernetes_dry_run_script_verifier_json_reports_corruption(tmp_path: Path) -> None:
    build_result = subprocess.run(
        [
            sys.executable,
            str(REPO_ROOT / "scripts" / "kubernetes_dry_run.py"),
            "--json",
            "--target",
            "k3s",
            "--artifact-dir",
            str(tmp_path),
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    assert build_result.returncode == 0, build_result.stderr + build_result.stdout
    (tmp_path / "summary.json").write_text("corrupt\n", encoding="utf-8")

    result = subprocess.run(
        [
            sys.executable,
            str(REPO_ROOT / "scripts" / "kubernetes_dry_run.py"),
            "--json",
            "--verify-artifact-dir",
            str(tmp_path),
        ],
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 1
    payload = json.loads(result.stdout)
    assert payload["ok"] is False
    assert any("summary.json" in error for error in payload["errors"])


def test_ci_has_manual_kubernetes_proof_artifact_workflow() -> None:
    workflow_path = REPO_ROOT / ".github" / "workflows" / "kubernetes-proof.yml"

    workflow = workflow_path.read_text(encoding="utf-8")

    assert "workflow_dispatch:" in workflow
    assert "pull_request:" not in workflow
    assert "push:" not in workflow
    assert "runs-on: [self-hosted, linux, x64, k3s]" in workflow
    assert "actions/setup-python" not in workflow
    assert ".venv/bin/python scripts/kubernetes_render_check.py --strict" in workflow
    assert "--target k3s" in workflow
    assert "--require-cluster" in workflow
    assert "--require-amd-gpu" in workflow
    assert "--artifact-dir local-kubernetes-proof/k3s" in workflow
    assert (
        ".venv/bin/python scripts/kubernetes_dry_run.py --json --verify-artifact-dir "
        "local-kubernetes-proof/k3s"
    ) in workflow
    assert (
        "- name: Verify k3s proof bundle\n"
        "        if: always()\n"
        "        run: |\n"
        "          set -o pipefail\n"
        "          set +e\n"
        "          mkdir -p local-kubernetes-proof/k3s\n"
        "          .venv/bin/python scripts/kubernetes_dry_run.py --json --verify-artifact-dir "
        "local-kubernetes-proof/k3s | tee local-kubernetes-proof/k3s/verification.json\n"
        "          status=${PIPESTATUS[0]}\n"
        '          exit "$status"'
    ) in workflow
    assert "- name: Summarize k3s proof bundle\n        if: always()" in workflow
    assert "find local-kubernetes-proof/k3s -maxdepth 1 -type f -print | sort" in workflow
    assert "cat local-kubernetes-proof/k3s/checksums.txt" in workflow
    assert "actions/upload-artifact@v4" in workflow
    assert "local-kubernetes-proof/k3s/k3s.yaml" in workflow
    assert "local-kubernetes-proof/k3s/k3s.dry-run.json" in workflow
    assert "local-kubernetes-proof/k3s/proof-command.txt" in workflow
    assert "local-kubernetes-proof/k3s/run-metadata.json" in workflow
    assert "local-kubernetes-proof/k3s/summary.json" in workflow
    assert "local-kubernetes-proof/k3s/checksums.txt" in workflow
    assert "local-kubernetes-proof/k3s/verification.json" in workflow


def test_kubernetes_proof_workflow_check_script_runs() -> None:
    result = subprocess.run(
        [sys.executable, str(REPO_ROOT / "scripts" / "kubernetes_proof_workflow_check.py")],
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr + result.stdout
    assert "kubernetes proof workflow OK" in result.stdout
