"""Phase M5.4.3: Ansible inventory generator из mDNS-discovered peers.

Wizard collects (hostname, address) peers через `agmind.cluster.detect.discover`.
Если user отмечает "Replicate to peers", ConfirmScreen.action_apply вызывает
этот helper — он создаёт inventory YAML в формате `ansible/inventory/cluster.yml`,
готовый для `ansible-playbook -i <path> install.yml`.

Local node всегда master (полный stack). Peers — workers (llama-llm only).
"""

from __future__ import annotations

from pathlib import Path

from agmind.core.files import write_text_atomic
from agmind.core.logging import logger

log = logger(__name__)

DEFAULT_INVENTORY_PATH = Path.home() / ".local" / "share" / "agmind" / "cluster-inventory.yml"


def generate_inventory_yaml(
    peers: list[tuple[str, str]],
    master_hostname: str = "agmind-master",
    master_address: str = "127.0.0.1",
    master_profiles: tuple[str, ...] = ("core", "observability"),
) -> str:
    """Render multi-node Ansible inventory YAML.

    Args:
        peers: list of (hostname, address) от mDNS discover.
        master_hostname: identity локального node (= current host).
        master_address: IP для master в inventory.
        master_profiles: profiles для master (полный stack).

    Returns YAML text — caller сам решает куда сохранить.
    """
    lines = [
        "# AGmind cluster inventory — generated by setup wizard (M5.4.3).",
        "# Regenerated каждый `agmind setup` run если выбран replicate-to-peers.",
        "# Hand-edits будут перезаписаны.",
        "",
        "all:",
        "  vars:",
        "    agmind_install_dir: /opt/agmind",
        "    agmind_data_dir: /var/lib/agmind",
        "    agmind_lan_only: true",
        "    agmind_mdns_enabled: true",
        "",
        "  children:",
        # Parent group = master ∪ workers so install.yml's `hosts: agmind_nodes` plays
        # actually match every node (audit arch-cluster HIGH — without it the multi-node
        # install bootstrapped nothing).
        "    agmind_nodes:",
        "      children:",
        "        agmind_master:",
        "        agmind_workers:",
        "",
        "    agmind_master:",
        "      hosts:",
        f"        {master_hostname}:",
        f"          ansible_host: {master_address}",
        "          agmind_role: master",
        "          agmind_profiles:",
    ]
    for profile in master_profiles:
        lines.append(f"            - {profile}")
    lines.append("          agmind_cluster_role: coordinator")
    lines.append("")
    lines.append("    agmind_workers:")
    if not peers:
        lines.append("      hosts: {}  # no peers detected at wizard time")
    else:
        lines.append("      hosts:")
        for hostname, address in peers:
            slug = _slug(hostname)
            lines.append(f"        {slug}:")
            lines.append(f"          ansible_host: {address}")
            lines.append("          agmind_role: worker")
            lines.append("          agmind_profiles:")
            lines.append("            - core")
            lines.append("          agmind_cluster_role: worker")
            # Endpoint from the discovered IP, NOT "{slug}.local" — an FQDN hostname collapses
            # its dots to hyphens in the slug, yielding an unresolvable "<x>-<y>.local" (audit
            # arch-cluster L). The IP is already known and is always reachable.
            lines.append(f'          agmind_worker_endpoint: "http://{address}:8080"')
    return "\n".join(lines) + "\n"


def write_inventory(
    peers: list[tuple[str, str]],
    output_path: Path = DEFAULT_INVENTORY_PATH,
    **kwargs: object,
) -> Path:
    """Generate + persist inventory YAML. Returns path written.

    Создаёт parent dir если нет. Kwargs передаются в `generate_inventory_yaml`.
    """
    text = generate_inventory_yaml(peers, **kwargs)  # type: ignore[arg-type]
    write_text_atomic(output_path, text, mode=0o644)
    log.info("cluster inventory written: %s (%d peers)", output_path, len(peers))
    return output_path


def _slug(hostname: str) -> str:
    """Sanitize hostname для inventory key (ansible не любит спецсимволы)."""
    return hostname.replace(".local", "").replace(".", "-").replace(" ", "-").lower()


__all__ = [
    "DEFAULT_INVENTORY_PATH",
    "generate_inventory_yaml",
    "write_inventory",
]
